### ISSUE TITLE
Cannot run the bridge - chat not found with HTTP 400 status code

### ISSUE THREAD

**Issue by str0tta** [TeleBridge/TeleBridge#31] opened 2023-10-14 10:52 UTC
**Describe the bug**
I configured everything: the `.env` file, the `config.json` file (I put two chat: a private message chat and a group - important thing: I didn't add the bot in the group). I run `npm run telebridge`, but it fails (see below).

**To Reproduce**
1. Install the dependencies by using `npm i`
2. Configure `.env` & `config.json`
3. `npm run telebridge`

**Expected behavior**
It should run the bridge.

**Errors/Screenshot of the behavior in chat**
![image](https://github.com/TeleBridge/TeleBridge/assets/103881005/b61065cd-53d4-4875-826c-a68fb99b4912)

**Hosting Platform and NodeJS version**
- Ubuntu 20.04 on a VPS M from Contabo - the infrastructure is containerized with Docker
- NodeJS v18.17.0

**Additional context**
I already set the privacy mode to disabled.

`.env`:

```
DISCORDTOKEN=MTE2redacted
TGTOKEN=641redacted
MONGO_URI=mongodb://mongodb:27017/telegram
API_ID=redacted
API_HASH=f7redacted
```

`config.json`:

```json
{
    "bridges": [
        {
            "name": "PrivateChat",
            "discord": {
                "chat_id": "1155redacted"
            },
            "telegram": {
                "chat_id": "20redacted"
            },
            "hide": true,
            "disabled": false
        },
        {
            "name": "GroupChat",
            "discord": {
                "chat_id": "1155redacted"
            },
            "telegram": {
                "chat_id": "-100redacted"
            },
            "hide": true,
            "disabled": false
        }
    ],
    "ignore_bots": false,
    "owner": {
        "discord": "107redacted",
        "telegram": "80redacted"
    },
    "check_for_deleted_messages": false,
    "deleted_message_check_interval": 5
}
```

**Comment by AntogamerYT** [comment] 2023-10-14 11:30
Hey, thanks for making this issue!
I just checked the code, and i was stupid enough to not disable the bridge if the chat can't be found in the bot, lol, I'll push a fix very soon, thanks again

**Comment by AntogamerYT** [comment] 2023-10-14 11:40
Pushed a fix, please let me know if it works

**Comment by str0tta** [comment] 2023-10-14 13:30
Thanks for replying :) the bridge does not crash anymore, but the result is not what I thought it would have, because I thought that since you are using the NodeJS equivalent of the Telethon Python library, which is not a bot but a full Telegram client for Python, I would have also been able to bridge private chats to Discord channels (I have a private Discord server that I use to bridge my WhatsApp and Instagram chats by using [Matrix](https://matrix.org) as a middleware between Discord and the chats, it also has a Telegram bridge, but it's way more tricky to use for Telegram with the same use case).

Are you planning to move to a full Telegram client? A one which does not use a bot at all? Because otherwise I'm very sad to tell you that I wouldn't use your project, which definitely is very good (and you have my congratulations for it as it's very simple to integrate in an architecture) :/

**Comment by AntogamerYT** [comment] 2023-10-14 13:47
So you want to bridge private chats/DMs? Sadly, that's not TeleBridge's purpose, it was designed to bridge group chats.
You're right, i am using gramJS (`telegram`, yes, bots can use MTProto too), but i only use it because there's no good way to get a message's details from the Telegram Bot API to implement automatic message deleting, so i use MTProto to [manually fetch the messages](https://github.com/TeleBridge/TeleBridge/blob/989195b4befab2ebd2824fe86ee2f64d73f85a38/src/core/setup/main.ts#L290) and delete them from the Discord chat if they're not found.

I really like your idea, but you have to keep in mind that Telegram could limit/ban your account if they find out that a system like the one you described is running on a normal user account (they could also not care at all, but we're not telegram so we can't know for sure)

**Closed** 2024-01-17 14:04 UTC
